### ISSUE TITLE
Small Bug !

### ISSUE THREAD

**Issue by mikhoul** [DanielKamkha/PlayPauseFirefox#1]
Hi, 

Thanks for this usefull Add-on !  :smiley:

I found a small bug: When a tab with "play/pause" active is "selected/focussed" the dynamic "X"  **Close button** on the tab don't show up   :disappointed: 

An image worth thousand words, especially that english is not my native language ;-)
![http://i.imgur.com/tuspae1.png](http://i.imgur.com/tuspae1.png)
![http://i.imgur.com/4VkyPGu.png](http://i.imgur.com/4VkyPGu.png)

I'm not a real coder but with trial/error I found how to add my 2 favorites Internet Radio.
Feel free to add it in the next realese.

```
{ // Deezer
      regex: /.*\.deezer\.com.*/,
      selector: ".control-play",
      playingClass: "pause",
      create: PlayPause.SingleButtonGenericPlayer
    },
	{ // Jango
      regex: /.*\.jango\.com.*/,
      selector: "#btn-playpause",
      playingClass: "pause",
      create: PlayPause.SingleButtonGenericPlayer
    },
```

_Best Regards !_

**Comment by DanielKamkha** [comment]
Fixed. Going to AMO as v1.0.1

Thanks for your report!

**Comment by mikhoul** [comment]
Thanks for the quick fix,  :smiley:

 if I add other "radio stations" I will letyou know !

**Comment by mikhoul** [comment]
<ins>Just to let you know:</ins> Humm something is wrong, since the update Jango and Deezer no longer work :( 

Also the "X" to close the tabs don't work too...

I wil check later tonight or tomorrow on a new clean profile to try to know why it happen and will come back to tell you if I found !

Regards !

**Comment by mikhoul** [comment]
Reverted to 1.0 and it work fine so I don't know if it is a glitch from firefox or a real bug... Will try 1.01 later on new profile ;-)

**Comment by mikhoul** [comment]
Everything seem fine now, I think something was corupted in the Firefox add-on repertory so I deleted completly Play/pause and after a brand new install everything was fine ! :smiley:

Have a good Week-End !

**Comment by DanielKamkha** [comment]
Yeah, should have been a glitch on Mozilla CDN, happens. In addition, the update have not passed code review on AMO yet. This could have contributed to the CDN mess as well.

Also, thanks for updating your add-on review and removing all bug reports from it! Bug reports in add-on reviews are helpful, but they have a chance to be deleted by moderators.
