### ISSUE TITLE
Option to use regular tab text color

### ISSUE THREAD

**Issue by Fironet** [DanielKamkha/PlayPauseFirefox#10]
Love the play/pause feature, but I've found since installing the addon Youtube tab text is a grey color, rather than the regular color of the other tabs.

Nothing else has changed so I assume it's part of the addon affecting this. Would it be possible to add an option to retain the original tab color, or point me to how I could change this?

**Comment by DanielKamkha** [comment]
I'm not quite sure what do you mean by "regular color" in your scenario. But, anyway, this looks like a compatibility issue with another add-on. So I will investigate this.

**Comment by Fironet** [comment]
Here is an example of the grey text:

![grey tab text](https://cloud.githubusercontent.com/assets/6971981/14064612/f960acf0-f454-11e5-9fe7-a09d08184249.png)

And the regular tab text color:

![regular color](https://cloud.githubusercontent.com/assets/6971981/14064614/fdc77a30-f454-11e5-8d0e-8cd1a2de962f.png)

The only Addon I can think of that affects the tab styling is Tab Mix Plus, but I only have it set to 'Bold', without any custom color selection. Are you saying that Play/Pause doesn't have any color altering code?

**Comment by DanielKamkha** [comment]
Ye, right, Play/Pause has zero color-changing code. So it's a conflict with either TabMixPlus or that YouTube-specific add-on you mentioned.

**Comment by Fironet** [comment]
Found the culprit: the FxChrome theme. While I've used the same version of the theme for at least a year it wasn't until installing Play/Pause that the style activated for some reason.

It was this line:

    .tabbrowser-tab .tab-text:not([visuallyselected=true]):not(:-moz-lwtheme) {
      color: #3F3F3F;
    }

Made a Stylish tweak to override it (`color: inherit !important;`) and it's back to normal. Closing the issue.
