### ISSUE TITLE
Feature Request: Volume control

### ISSUE THREAD

**Issue by cheich** [DanielKamkha/PlayPauseFirefox#13]
Hi,

I know this plug-in is not meant to control the volume, however it would be a great feature :smile: 

Maybe the volume can be controlled via the mouse wheel while hover the mouse over a tab.
Or a small slider would appear if you press-and-hold on the native mute button or something like that.

I don't know if this is even possible.

**Comment by DanielKamkha** [comment]
I was going to say "yes, it's possible, but out of the scope for this extension". Then I googled around for anything with similar functionality and found... nothing.

So... definitely not happening for Play/Pause extension. But would be worth to create a separate extension. Thanks for the idea, I will research into this.

**Comment by cheich** [comment]
I've searched too and found nothing...

Nice! I will continue follow it :+1:
