### ISSUE TITLE
Moving tab duplicates play/pause icon

### ISSUE THREAD

**Issue by LucPestille** [DanielKamkha/PlayPauseFirefox#15]
This my be a bug specific to Spotify, but in FF 45.2.0 / Win 10, if I open a new tab, load Spotify and start something playing, then drag that tab to any other position, the play/pause icon is duplicated.

I suspect the title is updated when a tab is moved, and whatever you're doing to replace the play icon is wiped out.

![play](https://cloud.githubusercontent.com/assets/130498/17325881/ee5f7ff6-58a5-11e6-973d-9bf5b560c7e4.png)

**Comment by avi-jain** [comment]
Similar bug hence thought I'll just put it here.
When the tab is dragged to any other position, the native mute button of FF disappears.
FF - 43.0.1
![issue2](https://cloud.githubusercontent.com/assets/16825902/17996509/0d837df8-6b87-11e6-9489-0d77754bf244.PNG)
![issue1](https://cloud.githubusercontent.com/assets/16825902/17996508/0d5baf58-6b87-11e6-8650-d09bab4f99d7.PNG)

**Comment by DanielKamkha** [comment]
Could not reproduce with FF48+, Win7. Might be Win10 specific, will try that next.

**Comment by DanielKamkha** [comment]
Could not reproduce with FF50, Win10.
