### ISSUE TITLE
Relocate button in Tab Center

### ISSUE THREAD

**Issue by felipeebs** [DanielKamkha/PlayPauseFirefox#18]
It might be too early for that since Tab Center is an experimental feature, but the play/pause button is not very accessible using this mode.
- Too close to the edge: aligning to the right, no padding, makes going a little further with the cursor a bit of a frustration because the tab menu folds back in;
- Too small: you might accidentally click the close button. Firefox is moving towards a more touch-friendly layout, so in this case the button could be wrapped into a larger tap area like the close button (see images below)

![big tabs](https://cloud.githubusercontent.com/assets/2118758/17570568/4668ab4a-5f23-11e6-9f52-416f30bb2f91.png)
![compact tabs](https://cloud.githubusercontent.com/assets/2118758/17570567/4667c2d4-5f23-11e6-97d5-89031e7ae6a7.png)

Just an improvement suggestion, not much priority since this feature might not even be pinned in firefox's release.

**Comment by DanielKamkha** [comment]
Tab Center is certainly a thing to watch for. I will research into compatibility with Tab Center when it is upgraded from "experimental" to anything remotely "mainstream".
