### ISSUE TITLE
Unable to select tabs with play/pause icon

### ISSUE THREAD

**Issue by DrDentz** [DanielKamkha/PlayPauseFirefox#19]
Might be caused by Auto Unload Tab, Classic Theme Restorer, Multiple Tab Handler or Tab Mix Plus. The icon itself is still clickable and works.

**Comment by DanielKamkha** [comment]
Tested with each of the four listed extensions, could not reproduce the issue.

**Comment by DrDentz** [comment]
I found the culprit, it's this setting in Tab Mix Plus:
> Mouse -> Mouse Gestures -> Mouse click (down and release) to select a tab

**Comment by DanielKamkha** [comment]
I'll investigate this.

**Comment by DanielKamkha** [comment]
Fixed the "unable to select" bug.

A small compatibility issue still remains: if "Mouse click (down and release) to select a tab" is enabled in TabMixPlus, clicking on the Play/Pause indicator selects the tab (in addition to toggling play/pause).
