### ISSUE TITLE
Iheart radio

### ISSUE THREAD

**Issue by mikhoul** [DanielKamkha/PlayPauseFirefox#2]
Not a issue but the code for "Iheart radio" :smiley:

```
{ // Iheart Radio
      regex: /.*\.iheart\.com.*/,
      selector: "button.playing.btn-circle.medium.play",
      playingClass: "pause",
      create: PlayPause.SingleButtonGenericPlayer
    },
```

**Comment by mikhoul** [comment]
Another one for "Slacker Radio" this one work well <ins>**but**</ins> always stay with the "pause button" on the tab... maybe you are able to figure why ?  :confused:

```
{ // Slacker
      regex: /.*\.slacker\.com.*/,
      selector: "a.play, a.pause",
	  playingClass: "pause",
      create: PlayPause.SingleButtonGenericPlayer
    },
```

Just using a.play work fine too but in my trial/error process I tried both selector ant it work fine but no need for 2. :wink:

**Comment by mikhoul** [comment]
I'm not able to find the "right" selector for Songza, I really appreciate if you can help me to find it.

Here's what I have found but it did not work ? ::disappointed::
```
{ // Songza
      regex: /.*\.songza\.com.*/,
      selector: "miniplayer-control-play-pause",
      playingClass: "pause",
      create: PlayPause.SingleButtonGenericPlayer
    },
```

Regards !

**Comment by mikhoul** [comment]
Closed by misstake, sorry !

**Comment by DanielKamkha** [comment]
Ugh, well, how do I test the thing with the iHeatRadio? Its site spams me with 404 error pages, endlessly. Is it US-only?

**Comment by mikhoul** [comment]
I'm in Canada but I always use **Proxmate** since it's free and very reliable, you just install the add-on https://addons.mozilla.org/en-US/firefox/addon/proxmate/ and the packages for the site you want after on this page: https://proxmate.me/packages/ (including Songza and many others sites)

This addon is very clever it use a proxy **ONLY** for the connexxion/login on the website you choose so it don't slowdown the browsing on the whole site. You will appearas if you were in USA.

Best thing also it's seem easy to build packages for new sites in JS evrything is Opensource: https://github.com/dvcrn

I should learn **JS** I will lose less time tweaking script or add-on than just going with trial/errors 


Oh my bad I did not think there was partial support for Songza so I did not see it ::scream_cat::
I will take a look this week at the partial support to see if I can "tweak" something from it ! 


Ihearth.com function well so no real need to test it but if you want with proxmate you will be able ::kissing_closed_eyes::

**Comment by DanielKamkha** [comment]
Nope, tried Proxmate, it does not work for me. I'll toy around with some other proxy or VPN solutions instead.

**Comment by DanielKamkha** [comment]
OK, got iHeartRadio working, guess the issue wasn't country-related. Will push to AMO shortly.

**Comment by DanielKamkha** [comment]
By the way, just from the top of my head, the "always pause button" issue you're having with Slacker code might be caused by incorrect 'playingClass' value. This should be a CSS class name that the player button has *while* the music is playing.

**Comment by DanielKamkha** [comment]
Got Proxmate working. Toyed around with Songza. Weird UI (from the internal JS perspective). There seems to be a single play-pause button. But it's visual is determined by visibility of two underlying elements. And click event is handled for the whole panel of player buttons, not per-button.

All-in-all, no quick solution, postponing Songza again. I'll got over other players first.

**Comment by mikhoul** [comment]
Thanks a lot,  ::smiley::

At least you see the same thing I was seiing in Sonza. ::wink::

**Comment by DanielKamkha** [comment]
Slacker support goes to AMO as v1.0.3. Was a bit tricky, that one, but not as weird as Songza. 

And, yes, many thanks for you contributions, mikhoul!
