### ISSUE TITLE
Site suggestions

### ISSUE THREAD

**Issue by ninep9up** [DanielKamkha/PlayPauseFirefox#25]
A great extension, though it really borrows me a few sites aren't supported
Would be really nice if you could add support for these
vk.com 
music.yandex.com
radio.yandex.com

**Comment by DanielKamkha** [comment]
Added support for Yandex Music: https://github.com/DanielKamkha/PlayPauseFirefox/commit/ac4cb6549a401e74ee3ebde33e0a03327aed6ec7

**Comment by DanielKamkha** [comment]
Investigated Yandex Radio. Detecting playing/paused state their seems to be difficult. Not adding anything for it yet.

**Comment by Daerdemandt** [comment]
TED talks - it works fine with "Enable Play/Pause for embedded videos", but maybe it should also work without

**Comment by ninep9up** [comment]
I think a support for player.fm would be wise.

**Comment by DanielKamkha** [comment]
Added support for vk.com

**Comment by DanielKamkha** [comment]
Added support for player.fm
