### ISSUE TITLE
Firefox v53 breaks tab functionality

### ISSUE THREAD

**Issue by Fironet** [DanielKamkha/PlayPauseFirefox#28]
Just updated to v53 on the Developer version of Firefox and noticed Youtube and native HTML5 videos no longer have the play/pause icon in the tabs. Unsure if there is any alternate beta version of PlayPause available but thought I'd report the issue. Great addon.

**Comment by DanielKamkha** [comment]
Fixed: https://github.com/DanielKamkha/PlayPauseFirefox/commit/e37b391cf24e487d40abb555c3ca9290b0f1b9ee
