### ISSUE TITLE
Problem with Deezer

### ISSUE THREAD

**Issue by ArnaudOdinot** [DanielKamkha/PlayPauseFirefox#29]
The add-on is having a strange behavior with Deezer for a few months. The Pause button is here and works when you click it (pauses the song) but it doesn't change into a Play button. Also the hotkey doesn't work with Deezer.

**Comment by DanielKamkha** [comment]
Fixed: https://github.com/DanielKamkha/PlayPauseFirefox/commit/c49d58055b62abf68c6b9c7676504372d417dac2
