### ISSUE TITLE
Clicking on the indicator does switch you to that tab (Firefox 42.0)

### ISSUE THREAD

**Issue by codemateSamiM** [DanielKamkha/PlayPauseFirefox#3]
Can not control the playback in non-active tabs.

**Comment by CoolBlueSam** [comment]
Just installed. And tried it on youtube as well as pandora. It indeed switched tabs.

**Comment by DanielKamkha** [comment]
Tested in FF42, 43 and 44. Not reproducible. Do you guys have any extra addons that might interfere?

**Comment by CoolBlueSam** [comment]
Yep, i found the addon that is interfering. Tab Mix Plus. Any way to make it work along with it?

**Comment by DanielKamkha** [comment]
I will look into it.

**Comment by DanielKamkha** [comment]
Fixed. Goes to AMO as v1.0.8.
