### ISSUE TITLE
Tab title doesn't update with PPF enabled.

### ISSUE THREAD

**Issue by erasedff** [DanielKamkha/PlayPauseFirefox#31]
Tab title stays the same when the PPF first detects media content. For example when you start playing a YT playlist and switch to the next video, tab title will be stuck with the name of the first video/page with media content. Happens on SoundCloud as well. Probably happens on all other sites as well but I only tried YT and soundcloud. If I disable PPF while the content is playing, tab title instantly updates to the proper one.
Not having tab title updated when the next song starts playing is rather annoying. Other than this, the addon works fine.
Firefox 53-55.

**Comment by DanielKamkha** [comment]
Fixed: https://github.com/DanielKamkha/PlayPauseFirefox/commit/91b8edf499142f3795a5233a6d5e3a0894d185d5
