### ISSUE TITLE
Pandora's new layout required me to turn on Enable Embedded Option

### ISSUE THREAD

**Issue by ThatOneGuyDotNet** [DanielKamkha/PlayPauseFirefox#32]
With Pandora's new layout that was launched in the last week or two I stopped getting the Pause/Play button on their site.  Never even noticed there were options for this extension but discovered them and found that the Enabled Embedded option fixed the issue, not sure if you need to change something in the code to get it to come on by default again, since most users are unlikely to dig that much.  I'm glad I did because I also discovered the Pause/Play shortcut option, which is awesome!

Thanks for such a simple, useful extension!

FF51, Win10.  Updated to latest FF52 and same behavior (with an added "bonus" of having to go turn the setting off and on again to get the button to show up)

**Comment by DanielKamkha** [comment]
Fixed. Goes to AMO as v1.2.8.
