### ISSUE TITLE
Respond to media hotkeys

### ISSUE THREAD

**Issue by thomas479** [DanielKamkha/PlayPauseFirefox#36]
I would like to have this addon respond to the media hotkeys on my keyboard.  
I was hoping this would work via the "Configure Hotkey" option, but this does not work.

**Comment by svnpenn** [comment]
@thomas479, you can use the "Media Keys" add-on instead:

http://addons.mozilla.org/firefox/addon/media-keys

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/86

**Comment by thomas479** [comment]
Thanks!
