### ISSUE TITLE
Will switch to another station instead of pause at iHeartRadio

### ISSUE THREAD

**Issue by jesse23** [DanielKamkha/PlayPauseFirefox#38]
1. Go to iHeartRadio ( https://www.iheart.com/ )
2. Click "My Stations".
3. Play sons.
4. Try to click pause button on tab.

Result: instead of pause, It will switch to another channel and try to play.

**Comment by DanielKamkha** [comment]
iHeartRadio support seems to be completely broken at the moment, due to UI redesign on the site.

**Comment by DanielKamkha** [comment]
Fixed in v1.2.10, in review on AMO.

**Comment by jesse23** [comment]
Nice - Thank you!
