### ISSUE TITLE
(radio / podcast / audio stream) franceculture.fr support

### ISSUE THREAD

**Issue by jesus2099** [DanielKamkha/PlayPauseFirefox#39]
I have not studied how this plugin works but it doesn’t trigger on http://franceculture.fr website (French radio replays):

- https://www.franceculture.fr/personne-yasujiro-ozu.html (**where we see the play/pause should be tied/linked to the purple bottom player bar**)
- https://www.franceculture.fr/emissions/la-methode-scientifique/la-science-fiction-selon-gerard-klein
- https://www.franceculture.fr/emissions/les-pieds-sur-terre/polemique-la-chapelle

**Comment by jesus2099** [comment]
A quick look on https://github.com/DanielKamkha/PlayPauseFirefox/blob/master/data/play-pause-detect.js tells me that I should provide that kind of info:

The player button is like:

- while playing: `#player button.player-button.play.playing`
- while not playing: `#player button.player-button.play:not(.playing)`

So, maybe:

```js
{ // France Culture
	regex: /.*franceculture\.fr.*/,
	selector: "#player button.player-button.play",
	playingClass: "playing",
	// …
},
```

**Comment by DanielKamkha** [comment]
Done.

**Comment by jesus2099** [comment]
Thanks very much, your script is so well done it just needed some settings!

**Comment by jesus2099** [comment]
Thanks very much @DanielKamkha.
I’ve been using it and it works really great!
