### ISSUE TITLE
Global hotkey for toggling all pages?

### ISSUE THREAD

**Issue by jordantucker** [DanielKamkha/PlayPauseFirefox#4]
Is it possible to make a global hotkey, e.g. Ctrl+Alt+P, for toggling the play/pause state of all tabs? This is what I miss from an older plugin that only worked for Pandora. Thanks! (I'd call this a feature request instead of an issue but I don't know how to do that in github.)

**Comment by DanielKamkha** [comment]
Yes, that's certainly possible. But I'm not quite sure what do you mean by "toggling the play/pause state of all tabs". Do you mean that state changes to exact opposite for all tabs: paused tabs start playing and all playing tabs get paused, simultaneously? Or some other logic?

**Comment by jordantucker** [comment]
That would work, at least for my use case.

**Comment by DanielKamkha** [comment]
Implemented by https://github.com/DanielKamkha/PlayPauseFirefox/commit/816e825b4ea62b6d15e6880e9b87eec4c86b7869

**Comment by DanielKamkha** [comment]
Went to AMO as v1.1.0.
