### ISSUE TITLE
WebExtensions version, Firefox 57

### ISSUE THREAD

**Issue by captainhook** [DanielKamkha/PlayPauseFirefox#40]
Hi,
Is there a WebExtensions version in the works for this addon? Firefox 57 is around the corner, and I would like to see this addon live on.

**Comment by DanielKamkha** [comment]
Yes, the transition to WebExtensions is imminent. However, it does not come without a cost: WebExtensions are not allowed to meddle with tab titles, so the play/pause button/indicator has to go. The functionality survives, though, and the plan is to hook it to the "mute" button instead.

This would be a breaking change for the users, me myself included. So the plan is to publish the WebExtensions version only a few weeks in advance of the FF57 release (mid-November), as a trade-off between maximizing the lifetime of the good old clicky indicator and leaving people stranded without a working version at all.

**Comment by marsjaninzmarsa** [comment]
Have you tried requesting missing WebExtensions API-s on Bugzilla?

**Comment by DanielKamkha** [comment]
No, and I did not even realize I can. Can I? WebExtensions API seem to be just a subset of Chrom(ium) extensions API. Interactive tab titles are just not there. Chrome itself does not even have a "mute" button, just an indicator icon.

Regardless,  please feel free to request that the APIs if you think it'd work. I'm not going to do it myself. Designing an API and pushing the proposal through a bunch of people who don't care looks very much like my day job already.
