### ISSUE TITLE
Pressing Pause reduces volume and doesn't pause until you switch to that tab

### ISSUE THREAD

**Issue by CoolBlueSam** [DanielKamkha/PlayPauseFirefox#6]
So until now it was working fine (thanks for the Tabmix fix). However I think after recent firefox upgrade (43.0.4), the pause has stopped working. This is what happens

- I have pandora running in tab
- I click on Pause
- Volume of the music goes down, however music doesn't pause
- If I go to the pandora tab then the music pauses.

Side issues:
- I don't see Play/Pause for youtube. 
- Gifs on imgur load in paused state. E.g. http://i.imgur.com/APNNMtb.gifv

**Comment by DanielKamkha** [comment]
Is the volume issue Pandora-specific? Or universal?

Also, Play/Pause should not affect gifs in any way. Please double check, disable/enable Play/Pause, etc.

**Comment by CoolBlueSam** [comment]
8tracks works great. So does soundcloud. So looks like Pandora specific.
Amazon prime page, it works (but the icons don't change between play and pause). However if you go to amazon music library play/pause button doesn't show up (Just like youtube).

Yea gifs seems like it is because of the way they are embedded. So please ignore.

**Comment by CoolBlueSam** [comment]
With firefox 44.0 it started working on Pandora.

However the issue with button not showing up on youtube is still there.

**Comment by DanielKamkha** [comment]
Fixed YouTube issue:
https://github.com/DanielKamkha/PlayPauseFirefox/commit/05f8cd099313ea67b621b5d9c8d1ef251ef17a2d

Goes to AMO as v1.1.1. In reviews at the moment.
