### ISSUE TITLE
Any hope for mixcloud support?

### ISSUE THREAD

**Issue by Narann** [DanielKamkha/PlayPauseFirefox#7]
Thanks for this plugin! I thought about this idea as I saw the play/mute icon on the firefox tabs.

Any hope for mixcloud support? :)

https://www.mixcloud.com/

Thanks in advance!

**Comment by DanielKamkha** [comment]
Done. Goes to AMO as v1.1.2. Pending review at the moment.

**Comment by Narann** [comment]
Wow! That was fast! Thanks a lot! :)
