### ISSUE TITLE
Youtube "Pause" symbol

### ISSUE THREAD

**Issue by cmhrky** [DanielKamkha/PlayPauseFirefox#9]
Hi,

Extension is working good but symbol not changes to 'Pause' video is playing on Youtube.

I'm using FF45, Windows 7.

Thanks.

**Comment by cmhrky** [comment]
![playing youtube](https://cloud.githubusercontent.com/assets/17867666/13852877/ed739118-ec6c-11e5-8666-d674822d35f9.jpg)
![paused youtube](https://cloud.githubusercontent.com/assets/17867666/13852876/ed6c05a6-ec6c-11e5-92f8-d7a084126843.jpg)


html5 youtube player

**Comment by cmhrky** [comment]
Hi,

When using youtube in english language, "play/pause" indicator is working good. But if i choosing to turkish or other language, indicator is not working. And sometimes extension is not responding.

While using I realized to this situation.

Also the "Media Keys" with the extension, they're a very good pair. Many thanks for all your hard work.

Best regards.

**Comment by rcmero** [comment]
I believe the reason why this is happening is because YouTube already adds a Play symbol to the beginning of the title when a video is playing. This extension then doesn't know how to deal with that.

**Comment by DanielKamkha** [comment]
Thanks for the detailed description of the bug. Your hint about "language dependence" is very helpful. I'm fixing this in the next release.

**Comment by DanielKamkha** [comment]
Goes to AMO as v1.1.5. In review queue at the moment.
